replicaCount: 1

image:
  repository: "396913737205.dkr.ecr.us-east-1.amazonaws.com/ai-analyzer"
  tag: 58-2d4ec67

autoscaling:
  enabled: false

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
