replicaCount: 3

image:
  repository: "396913737205.dkr.ecr.us-east-1.amazonaws.com/order-service"
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

ingress:
  enabled: true
  host: "order-service.example.com"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
