replicaCount: 1

image:
  repository: "396913737205.dkr.ecr.us-east-1.amazonaws.com/order-service"
  tag: 80-137fce8

autoscaling:
  enabled: false

ingress:
  enabled: false
  host: "dev.order-service.example.com"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
