replicaCount: 2

image:
  repository: "REPLACE_WITH_ECR_REPO_URL/product-service"
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

ingress:
  enabled: true
  host: "staging.product-service.example.com"
