replicaCount: 2

image:
  repository: "396913737205.dkr.ecr.us-east-1.amazonaws.com/product-service"
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

ingress:
  enabled: true
  host: "staging.product-service.example.com"
