replicaCount: 2

image:
  repository: "REPLACE_WITH_ECR_REPO_URL/api-gateway"
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

ingress:
  enabled: true
  host: "staging.api.example.com"
