replicaCount: 2

image:
  repository: "396913737205.dkr.ecr.us-east-1.amazonaws.com/api-gateway"
  tag: "latest"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5

ingress:
  enabled: true
  host: "staging.api.example.com"
