replicaCount: 1

image:
  repository: "396913737205.dkr.ecr.us-east-1.amazonaws.com/api-gateway"
  tag: 10-bfae099

autoscaling:
  enabled: false

ingress:
  enabled: true
  host: "dev.api.example.com"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi
